#!/usr/bin/env bash
# Installs and configures a haproxy server
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo bash -c '
echo "
frontend http_front
        bind *:80
        default_backend http_back
backend http_back
        balance roundrobin
        server 1697-web-01 35.243.225.80:80 check
        server 1697-web-02 52.91.161.229:80 check
" > /etc/haproxy/haproxy.cfg'
sudo bash -c 'echo "ENABLED=1" > /etc/default/haproxy'
sudo service haproxy restart
