#!/usr/bin/env bash
# fixes listening issues on nginx server
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i '0,/octet-stream;/ !b;//a\include /etc/nginx/sites-enabled/*.*;' /etc/nginx/nginx.conf
sudo service nginx restart
