#!/usr/bin/env bash
# this program uses a nested loop to print hours of the day.
i=0
j=1
while [ $i -le 12 ]
do
	echo "Hour: $i"
	while [ $j -le 59 ]
	do
		echo $j
		j=$(( j + 1 ))
	done
	j=1
	i=$(( i + 1 ))
done
