#!/usr/bin/env bash
# this program prints information on a file.
FILENAME="holbertonschool"
if [ -e $FILENAME ]
then
	echo "holbertonschool file exists"
	if [ -s $FILENAME ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $FILENAME ]
	then
		echo "holbertonschool file is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
